language: android

jdk:
  - oraclejdk7
  - oraclejdk8

android:
  components:
  - android-23
  - tools
  - build-tools-23.0.2
  - extra-android-m2repository

script:
  - ./gradlew clean check

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "Xcus68OpgLX4sY0jL/+bG3+3rj4zkNiE+W3Q62GMnzAzBScPgKtSNgIkctmE2nLESAOlPKVL49vvm1iBfML/E+6N5mNE9KW/wjcijIDxRmQ3bVQ1OI33BftwkBV5uvWR/up8hLHp7NYHn8kr9Zl9aGDfXxLucrKcK3SfTdznQxMAnK0UzLnXCwN/P/wUS4aWYFwog2649MxYkxTwQmD/9OhyD1szC9MmEBxTYlGyituZN6FvSSWIlx1n+x/RT9Uq2W+jftdPv5ZIRAisoUgaOBoaeXlwIbpo84dp9tDDsYWeGAmekgePZtJ7yf+rG6kf5lqDxAE+CA5RCpIzn5Pv+YK/prPcOP1ouDP3pI0HOMUWLpwxSuta4RWA+qLv36F9MgRReLZZ041Xx3eRzLWK6BUDT7cjqIzQmc3xREtVg87lxY2S7H8MAEkzSMfffsAd3pGX/NDzomp56nBxpNCj+YY+1SC0KXn8C+J+8H99IgkezhwlZueOJerxkcm7MwlFjjUuDOYyLmNYAhZRPxwOcVZDwH6+2x5Pp4wC8YJTgpg2tLNsOZ5os7xniXDm70egEqZQUO/1W642Zp8+FedymAQfSsTW6QOGpe8mT+anQOfnz2K94Pm+M4OpkIJ2UPe+ps2zNhb7+S3Kyec+zEKDAmupA8vvTqxInCFaiVKED6E="
    - secure: "T9CsssiBNlDt4u0nuhUllmNs68lVO4VvWp2lgsTrPo8PMqGDpOJZjD37ff125oba5AGux5TjwKa0Rt1yamedxMetcdssT+2B0X0gHFdWmrLs2D/LKh+kfHuakEhIF+EV+3HEVMPNiH/OeS0ykYzXEJPISBr9TknuAwKIOz3ERhe9ulhMkDGE2y74Ieswq1eADiE12DP5uM77UAcoj4+5jdus0P02S9UZWI8Hkx82oYLPdoHJ5NyvgOxlqgE5udrJdgVdRyinucwDK9pQWJsPfAwX0/Fj3lGFE994Q1vCEVtWLcXXHLlavy7s9GGz1P60wzlvXodbulSL1VbJwQv5g2OlRDf3mnvHVkRGv602smedDOdNt0+slbiLf+qZT4wkatv6yObaVEbOXcU9ZvcJt/ei/3A0OzRh0yut3vs+g8Qbrzq8F/DuKuwVobXtbH137UF9NPdVBAwfeeQQPmjtrmcw0x4eaYo+jwsB1w3d0plHwj5KM4/kINdph37VbY5J9UJAH3IX6gdPDj3dpn81Ij73gIHtoFqVFLsQ20BHlwJo4oLzxE+ts8eqZ7nzL9djYe61mY5bGBlVmsLXacndlOvfUm1KfsrwZjue98KV+VqTzsCkjWmkIoITAgn4FaRFl/3o1NZ7bPYJeQab7UgnrV7R/c1jpg0+dmoXELnGdUE="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
